/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutDialog.java
 *
 * Created on Feb 23, 2010, 10:01:30 PM
 */

package net.padlocksoftware.ui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.padlocksoftware.padlock.license.PadlockState;

/**
 *
 * @author jason
 */
public class AboutDialog extends javax.swing.JFrame {

   private final LocalPadlockModel model;

    /** Creates new form AboutDialog */
    public AboutDialog(LocalPadlockModel model) {
      this.model = model;
      getRootPane().putClientProperty("apple.awt.brushMetalLook", Boolean.TRUE);
      initComponents();
      setIconImages(UIUtils.getIcons());
      updateState();
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    statusPanel = new net.padlocksoftware.ui.StatusPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    closeButton = new javax.swing.JButton();
    chooseButton = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();
    nameLabel = new javax.swing.JLabel();
    companyLabel = new javax.swing.JLabel();
    emailLabel = new javax.swing.JLabel();
    versionLabel = new javax.swing.JLabel();
    supportLabel = new javax.swing.JLabel();
    licenseFileLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("About Padlock Manager");
    setResizable(false);

    jLabel1.setText("Name:");

    jLabel2.setText("Company:");

    jLabel3.setText("Email:");

    jLabel4.setText("Major Version:");

    jLabel5.setText("Support Length:");

    closeButton.setText("Close");
    closeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        closeButtonActionPerformed(evt);
      }
    });

    chooseButton.setText("Choose...");
    chooseButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chooseButtonActionPerformed(evt);
      }
    });

    jLabel6.setText("License Location:");

    nameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    companyLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    emailLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    versionLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    supportLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    licenseFileLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(statusPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(jLabel6)
          .add(jLabel1)
          .add(jLabel2)
          .add(jLabel3)
          .add(jLabel4)
          .add(jLabel5))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(nameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
          .add(companyLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
          .add(emailLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
          .add(versionLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
          .add(supportLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, licenseFileLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(chooseButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
          .add(closeButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(nameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(companyLabel))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(emailLabel))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(versionLabel))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(supportLabel))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel6)
          .add(licenseFileLabel)
          .add(chooseButton))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 34, Short.MAX_VALUE)
        .add(closeButton)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(statusPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
    );

    layout.linkSize(new java.awt.Component[] {companyLabel, emailLabel, licenseFileLabel, nameLabel, supportLabel, versionLabel}, org.jdesktop.layout.GroupLayout.VERTICAL);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
      setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void chooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtonActionPerformed
      JFileChooser chooser = new JFileChooser();
      chooser.setDialogType(JFileChooser.OPEN_DIALOG);
      chooser.setDialogTitle("Padlock License Selection");
      chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
      chooser.setMultiSelectionEnabled(false);
      FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "License Files (*.lic)", "lic");
      chooser.setFileFilter(filter);

      int value = chooser.showDialog(this, "Select");
      
      if (value == JFileChooser.APPROVE_OPTION) {
         File selectedFile = chooser.getSelectedFile();
         model.setLicenseLocation(selectedFile.getPath());
         updateState();
      }
    }//GEN-LAST:event_chooseButtonActionPerformed


    private void updateState() {
      PadlockState state = model.getState();

      nameLabel.setText(" " + state.getName());
      companyLabel.setText(" " + state.getCompanyName());
      emailLabel.setText(" " + state.getEmail());
      licenseFileLabel.setText(" " + model.getLicenseLocation());
      
      int version = state.getMajorVersion();
      if (version == 0) {
        versionLabel.setText(""); 
      } else versionLabel.setText(" " + Integer.toString(version));

      int years = state.getSupportLength();

      if (years == 0) {
         supportLabel.setText("");
      } else {

         supportLabel.setText(" " + Integer.toString(years) + " year" +
              (years != 1 ? "s" : ""));
      }

      if (state.isValid()) {
         statusPanel.info("The Padlock license file is valid.  Thanks for your purchase!");
      } else if (state.getLicense() != null) {
         statusPanel.warn(state.getStateDescription());
      } else statusPanel.warn("Please select your Padlock license file.");
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton chooseButton;
  private javax.swing.JButton closeButton;
  private javax.swing.JLabel companyLabel;
  private javax.swing.JLabel emailLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel licenseFileLabel;
  private javax.swing.JLabel nameLabel;
  private net.padlocksoftware.ui.StatusPanel statusPanel;
  private javax.swing.JLabel supportLabel;
  private javax.swing.JLabel versionLabel;
  // End of variables declaration//GEN-END:variables

}
