/**
 * Copyright (c) 2009 Padlock Software LLC.
 *
 * The contents of this file are private and contain confidential trade secrets.
 * Any viewing, distribution, or usage is strictly prohibited.
 */
package net.padlocksoftware.ui;

import com.imagine.component.calendar.CalendarComboBox;
import com.imagine.component.calendar.CalendarComponent;
import java.util.Date;

/**
 *
 * @author jason
 */
public class DatePicker extends javax.swing.JPanel {

    CalendarComboBox calendar;
    
    /** Creates new form DatePicker */
    public DatePicker() {
        initComponents();

        calendar = new CalendarComboBox();
        CalendarComponent calendarComponent = calendar.getCalendarComponent();
        calendarComponent.setCalendarProperty(CalendarComponent.FIRST_DAY_OF_WEEK, new Integer(java.util.Calendar.SUNDAY));
        calendarComponent.setCalendarProperty(CalendarComponent.STATUS_PANEL_TODAY_LABEL, "Today: {MM.dd.yyyy}");
        calendarComponent.getCalendarSelectionModel().setEmptySelectionAllowed(true);
//        calendarComponent.setCalendarProperty(CalendarComponent.STATUS_PANEL_NONE_LABEL, "None");
        calendar.setDateFormat("EEE, d MMM yyyy");//
//        calendarComponent.setCalendarProperty(CalendarComponent.SHOW_STATUS_PANEL, new Boolean(true));

        this.add(calendar);
    }

    public void setDate(Date d) {
        calendar.setDate(d);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}
