/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MoveToCategoryDialog.java
 *
 * Created on Jan 26, 2010, 1:24:54 PM
 */

package net.padlocksoftware.ui;

import net.padlocksoftware.ui.plugins.CategoryPlugin;

/**
 *
 * @author jason
 */
public class MoveToCategoryDialog extends javax.swing.JDialog {

    private final PadlockModel model;
    private final String licenseName;

    /** Creates new form MoveToCategoryDialog */
    public MoveToCategoryDialog(java.awt.Frame parent, PadlockModel model, String licenseName) {
        super(parent, true);
        initComponents();
        setIconImages(UIUtils.getIcons());
        this.licenseName = licenseName;
        this.model = model;
        statusPanel.info("Move " + licenseName + " to a new category");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    statusPanel = new net.padlocksoftware.ui.StatusPanel();
    moveButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    categoryField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Move to new category");
    setResizable(false);

    moveButton.setText("Move");
    moveButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        moveButtonActionPerformed(evt);
      }
    });

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    jLabel1.setText("New Category:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(cancelButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(moveButton))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(categoryField, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
        .addContainerGap())
      .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, moveButton});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(moveButton)
          .addComponent(cancelButton))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
      setVisible(false);
      dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed

      String category = categoryField.getText();
      if (category.length() == 0) category = null;

      CategoryPlugin catPlugin = (CategoryPlugin)model.getPlugin("net.padlocksoftware.ui.plugins.CategoryPlugin");

      catPlugin.setLicenseCategory(licenseName, category);
      setVisible(false);
      dispose();
    }//GEN-LAST:event_moveButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JTextField categoryField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JButton moveButton;
  private net.padlocksoftware.ui.StatusPanel statusPanel;
  // End of variables declaration//GEN-END:variables

}
