/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreferencesDialog.java
 *
 * Created on Feb 22, 2010, 9:40:42 AM
 */
package net.padlocksoftware.ui;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author jason
 */
public class PreferencesDialog extends javax.swing.JFrame {

   private final LocalPadlockModel model;

   /** Creates new form PreferencesDialog */
   public PreferencesDialog(LocalPadlockModel model) {
      this.model = model;
      getRootPane().putClientProperty("apple.awt.brushMetalLook", Boolean.TRUE);
      initComponents();
      setIconImages(UIUtils.getIcons());
      updateLabels();
      statusPanel.info("Changes will take effect on the next start.");
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    statusPanel = new net.padlocksoftware.ui.StatusPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    licenseLabel = new javax.swing.JLabel();
    keysLabel = new javax.swing.JLabel();
    licenseButton = new javax.swing.JButton();
    keysButton = new javax.swing.JButton();
    closeButton = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    templatesLabel = new javax.swing.JLabel();
    templatesButton = new javax.swing.JButton();

    setTitle("Padlock Manager Preferences");
    setResizable(false);

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setText("Licenses Folder:");

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Keys Folder:");

    licenseLabel.setText("jLabel3");
    licenseLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 70, 70)));

    keysLabel.setText("jLabel4");
    keysLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 70, 70)));

    licenseButton.setText("Choose...");
    licenseButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        licenseButtonActionPerformed(evt);
      }
    });

    keysButton.setText("Choose...");
    keysButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        keysButtonActionPerformed(evt);
      }
    });

    closeButton.setText("Close");
    closeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        closeButtonActionPerformed(evt);
      }
    });

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("TemplatesFolder:");

    templatesLabel.setText("jLabel4");
    templatesLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 70, 70)));

    templatesButton.setText("Choose...");
    templatesButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        templatesButtonActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(statusPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
          .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(jLabel2)
          .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
          .add(layout.createSequentialGroup()
            .add(licenseLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 365, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(licenseButton))
          .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
              .add(org.jdesktop.layout.GroupLayout.LEADING, templatesLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 365, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .add(keysLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 365, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(templatesButton)
              .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, closeButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, keysButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        .addContainerGap())
    );

    layout.linkSize(new java.awt.Component[] {keysLabel, licenseLabel, templatesLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

    layout.linkSize(new java.awt.Component[] {keysButton, licenseButton, templatesButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1)
          .add(licenseLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(licenseButton))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(keysLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(keysButton)
          .add(jLabel2))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel3)
          .add(templatesLabel)
          .add(templatesButton))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 36, Short.MAX_VALUE)
        .add(closeButton)
        .add(18, 18, 18)
        .add(statusPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
    );

    layout.linkSize(new java.awt.Component[] {keysButton, keysLabel, licenseButton, licenseLabel, templatesButton, templatesLabel}, org.jdesktop.layout.GroupLayout.VERTICAL);

    pack();
  }// </editor-fold>//GEN-END:initComponents

   private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
      this.setVisible(false);
   }//GEN-LAST:event_closeButtonActionPerformed

   private void licenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseButtonActionPerformed
      JFileChooser chooser = new JFileChooser(model.getLicenseFolder());
      chooser.setMultiSelectionEnabled(false);
      chooser.setDialogTitle("Set license folder");
      chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

      int val = chooser.showDialog(this, "Choose");

      if (val == JFileChooser.APPROVE_OPTION) {
         File folder = chooser.getSelectedFile();
         model.setLicenseFolder(folder);
         licenseLabel.setText(" " + folder.getPath());
      }
   }//GEN-LAST:event_licenseButtonActionPerformed

   private void keysButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keysButtonActionPerformed
      JFileChooser chooser = new JFileChooser(model.getKeyPairFolder());
      chooser.setMultiSelectionEnabled(false);
      chooser.setDialogTitle("Set keypair folder");
      chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

      int val = chooser.showDialog(this, "Choose");

      if (val == JFileChooser.APPROVE_OPTION) {
         File folder = chooser.getSelectedFile();
         model.setKeyPairFolder(folder);
         keysLabel.setText(" " + folder.getPath());
      }

   }//GEN-LAST:event_keysButtonActionPerformed

   private void templatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_templatesButtonActionPerformed
      JFileChooser chooser = new JFileChooser(model.getTemplateFolder());
      chooser.setMultiSelectionEnabled(false);
      chooser.setDialogTitle("Set template folder");
      chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

      int val = chooser.showDialog(this, "Choose");

      if (val == JFileChooser.APPROVE_OPTION) {
         File folder = chooser.getSelectedFile();
         model.setTemplateFolder(folder);
         templatesLabel.setText(" " + folder.getPath());
      }
   }//GEN-LAST:event_templatesButtonActionPerformed

   private void updateLabels() {
      licenseLabel.setText(" " + model.getLicenseFolder().getPath());
      keysLabel.setText(" " + model.getKeyPairFolder().getPath());
      templatesLabel.setText(" " + model.getTemplateFolder().getPath());
   }
   
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton closeButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JButton keysButton;
  private javax.swing.JLabel keysLabel;
  private javax.swing.JButton licenseButton;
  private javax.swing.JLabel licenseLabel;
  private net.padlocksoftware.ui.StatusPanel statusPanel;
  private javax.swing.JButton templatesButton;
  private javax.swing.JLabel templatesLabel;
  // End of variables declaration//GEN-END:variables
}
