/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatusPanel.java
 *
 * Created on Jan 20, 2010, 10:04:06 AM
 */
package net.padlocksoftware.ui;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author jason
 */
public class StatusPanel extends javax.swing.JPanel {

  URL infoURL = this.getClass().getResource("/net/padlocksoftware/ui/resources/info.png");
  ImageIcon infoIcon = new ImageIcon(infoURL);
  URL warnURL = this.getClass().getResource("/net/padlocksoftware/ui/resources/warn.png");
  ImageIcon warnIcon = new ImageIcon(warnURL);
  URL criticalURL = this.getClass().getResource("/net/padlocksoftware/ui/resources/critical.png");
  ImageIcon criticalIcon = new ImageIcon(criticalURL);

  /** Creates new form StatusPanel */
  public StatusPanel() {
    initComponents();
  }

  public void info(final String message) {
    SwingUtilities.invokeLater(new Runnable() {

      public void run() {
        label.setText(message);
        label.setIcon(infoIcon);
      }
    });
  }

  public void warn(final String message) {
    SwingUtilities.invokeLater(new Runnable() {

      public void run() {
        label.setText(message);
        label.setIcon(warnIcon);
      }
    });
  }

  public void critical(final String message) {
    SwingUtilities.invokeLater(new Runnable() {

      public void run() {
        label.setText(message);
        label.setIcon(criticalIcon);
      }
    });
  }

  public void info(final String message, final ImageIcon icon) {
    SwingUtilities.invokeLater(new Runnable() {

      public void run() {
        label.setIcon(icon);
        label.setText(message);
      }
    });

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    label = new javax.swing.JLabel();

    setBackground(new java.awt.Color(64, 64, 64));
    setPreferredSize(new java.awt.Dimension(377, 23));

    label.setForeground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel label;
  // End of variables declaration//GEN-END:variables
}
